const header=document.querySelector('header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30));const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));
document.querySelector('#hotelSearch').onclick=()=>{const p=document.querySelector('#hotelPlace').value.trim(),r=document.querySelector('#hotelResult');r.textContent=p?`Live hotel results for ${p} will appear here when the hotel API is connected.`:'Please enter a destination.'};
const modal=document.querySelector('#coachModal');document.querySelectorAll('[data-open="coachModal"]').forEach(b=>b.onclick=()=>modal.showModal());modal.querySelector('.close').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};document.querySelector('#coachForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),subject=encodeURIComponent(`Coach quote — ${d.get('date')} — ${d.get('passengers')} passengers`),body=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\nDate: ${d.get('date')}\nPassengers: ${d.get('passengers')}\n\nJourney details:\n${d.get('details')}`);location.href=`mailto:hello@royalroamtours.com?subject=${subject}&body=${body}`};
const booking=document.querySelector('#bookingModal'),steps=[...booking.querySelectorAll('.booking-step')],next=document.querySelector('#bookingNext'),back=document.querySelector('#bookingBack'),passengers=document.querySelector('#passengers'),grid=document.querySelector('#seatGrid'),help=document.querySelector('#seatHelp'),chosen=document.querySelector('#chosenSeats'),summary=document.querySelector('#bookingSummary'),taken=new Set(['1A','2D','4A','4B','7C','9D','11A']),selected=new Set();let step=1;
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function total(){return Number(passengers.value)}
function update(){const remaining=total()-selected.size;help.textContent=remaining?`Select ${remaining} more available ${remaining===1?'seat':'seats'}.`:'Perfect — your seats are ready.';chosen.textContent=[...selected].join(', ')||'—';next.disabled=step===2&&remaining!==0}
function seat(label){const b=document.createElement('button');b.type='button';b.textContent=label;b.className='seat';if(taken.has(label)){b.classList.add('taken');b.disabled=true}else b.onclick=()=>{if(selected.has(label)){selected.delete(label);b.classList.remove('selected')}else if(selected.size<total()){selected.add(label);b.classList.add('selected')}else toast(`Choose ${total()} seats, or remove one first`);update()};return b}
function buildSeats(){grid.replaceChildren();for(let row=1;row<=11;row++){['A','B'].forEach(x=>grid.append(seat(`${row}${x}`)));const n=document.createElement('span');n.textContent=row;grid.append(n);['C','D'].forEach(x=>grid.append(seat(`${row}${x}`)))}}
function show(n){step=n;steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));back.hidden=step===1||step===4;next.disabled=step===2&&selected.size!==total();next.textContent=step===1?'Choose seats →':step===2?'Passenger details →':step===3?'Review booking →':'Finish';booking.querySelector('.booking-body').scrollTop=0}
function reset(){passengers.value='2';selected.clear();['leadName','leadEmail','leadPhone'].forEach(id=>document.getElementById(id).value='');buildSeats();show(1);update()}
document.querySelectorAll('[data-direct-booking]').forEach(b=>b.onclick=()=>{reset();booking.showModal()});booking.querySelector('.booking-close').onclick=()=>booking.close();booking.onclick=e=>{if(e.target===booking)booking.close()};passengers.onchange=()=>{selected.clear();buildSeats();update()};back.onclick=()=>show(step-1);next.onclick=()=>{if(step===1)return show(2);if(step===2&&selected.size===total())return show(3);if(step===3){const fields=['leadName','leadEmail','leadPhone'].map(id=>document.getElementById(id));if(fields.some(f=>!f.value.trim()))return toast('Please complete all passenger details');summary.innerHTML=`Seats <b>${[...selected].join(', ')}</b><br>Green Line Coach Station, Victoria`;return show(4)}booking.close();toast('Booking test completed — no payment was taken')};buildSeats();update();
